### ISSUE TITLE
"TypeError: Invalid URL: 192.168.1.31/status.shtml"

### ISSUE THREAD

**Issue by peissl-at** [secanis/red-contrib-keba-parser#1]
Hello,

I just found the Keba Node. I am very pleased that someone has taken on this charging station. Unfortunately I get the following error message: "TypeError: Invalid URL: 192.168.1.31/status.shtml"

When I call up the url in the browser, I see the status page of the wallbox. I have a KEBA P30c.

Sunny greetings from Styria
Robert

**Comment by matthiasbaldi** [comment]
Ty for using it 👍 and for your feedback.
Question, did you entered the URL with "http://" or without?
I think I have to improve there some automatism.
Please try with http:// prefix.

**Comment by peissl-at** [comment]
Hello Matthias,

yes, with prefix it works! Many thanks for the hint.

Suggestions for improvement: The name of the node is not yet displayed. The values ​​are currently only "cut out". It would be nice if these values ​​are already prepared as numbers. And a node.status could show in gray, blue, green (unplugged, plugged, or charging), maybe even with the "realpower" attached. And red for network-connection errors, or error messages from the box, if these are available.
Are all just recommendations for future extensions.

Thank you for your work and sunny greetings!
Robert

**Comment by matthiasbaldi** [comment]
Hi Robert
Thank you for your feedback 👍 I appreciate that very much.
In the todays 0.2.0 release I think I integrated the most of your mentioned points.
Details you can see here: https://github.com/secanis/red-contrib-keba-parser/releases/tag/0.2.0
Note, that this is breaking because I parse now the numbers to floats.

If you have any other ideas or thoughts please let me know.

Greetings back, out of the snow ❄

**Comment by peissl-at** [comment]
Hi Matthias,

very impressive that you implemented my suggestions so quickly. 👍🏻
The node.status has also become very good. Many thanks for the great node. If I have further ideas i will be happy to get back to you.

Sunny greetings!
Robert

PS: It would be great if you also drive an Audi. For that I would also need a node. 🤣

**Comment by matthiasbaldi** [comment]
np... nope I drive a Nissan Leaf, may I also need one for that ✌
Btw did you ever had an error state on the charging station?

**Comment by peissl-at** [comment]
Nope, fortunately no errors so far. Do you ask because I indicated that above, or do you have any?

**Comment by matthiasbaldi** [comment]
Because you gave me the tip above... never had one. But then lets wait for one and hope that never one happens... 😀

**Comment by peissl-at** [comment]
I saw at loxone that they had integrated an error output for the Keba, so I suspected that it is possible.
But I also hope that we don't have to see that. 😉
