### ISSUE TITLE
Remove from Flow Library

### ISSUE THREAD

**Issue by knolleary** [secanis/red-contrib-keba-parser#2]
To remove this module from the Node-RED flow library, publish a new version to npm with the `node-red` keyword removed. You can then click the 'update module' link on its flow library page and the module *should* get removed. Any problems, let me know and I'll remove it manually.

**Comment by matthiasbaldi** [comment]
Thank you for the fast answer. The problem may is that this package still exists but on the new name.
So it is may not that easily possible to publish it again under the old name.
Is a big effort needed to remove it manually?

**Comment by knolleary** [comment]
I can remove it - just won't be able to do so immediately as I'm busy with other things right now. If there's no rush, then leave it with me.

**Comment by matthiasbaldi** [comment]
Perfect. Thank you. There is no rush.
Sorry for the circumstances. 😇

**Comment by knolleary** [comment]
Thanks for the nudge. Done.

**Comment by matthiasbaldi** [comment]
Thank you. Struggled today over the issue 😅
